<?php

// File generated from our OpenAPI spec

namespace Stripe\V2\Signals;

/**
 * The PaymentRetrySignal resource represents a single retry recommendation
 * generated by the ML scoring model.
 *
 * @property string $id Unique identifier for the signal.
 * @property string $object String representing the object's type. Objects of the same type share the same value of the object field.
 * @property string $created When this signal was created.
 * @property string $evaluation The evaluation that generated this signal.
 * @property bool $livemode Has the value <code>true</code> if the object exists in live mode or the value <code>false</code> if the object exists in test mode.
 * @property null|string $payment_intent The payment intent this signal relates to.
 * @property string $payment_record The payment record this signal relates to.
 * @property (object{action: string, reason: string}&\Stripe\StripeObject) $recommendation The retry recommendation.
 */
class PaymentRetrySignal extends \Stripe\ApiResource
{
    const OBJECT_NAME = 'v2.signals.payment_retry_signal';
}
