<?php

// File generated from our OpenAPI spec

namespace Stripe\V2\Signals;

/**
 * The PaymentRetryEvaluation resource represents an active or completed retry
 * monitoring session for a specific failed payment.
 *
 * @property string $id Unique identifier for the evaluation.
 * @property string $object String representing the object's type. Objects of the same type share the same value of the object field.
 * @property null|string $canceled_at When the evaluation was canceled, if applicable.
 * @property null|string $cancellation_reason Reason provided for canceling the evaluation.
 * @property string $created When the evaluation was created.
 * @property PaymentRetrySignal $latest_signal The PaymentRetrySignal resource represents a single retry recommendation generated by the ML scoring model.
 * @property bool $livemode Has the value <code>true</code> if the object exists in live mode or the value <code>false</code> if the object exists in test mode.
 * @property null|string $payment_intent The payment intent being evaluated, if provided instead of a payment record.
 * @property null|string $payment_record The payment record being evaluated.
 * @property string $status Current status of the evaluation.
 */
class PaymentRetryEvaluation extends \Stripe\ApiResource
{
    const OBJECT_NAME = 'v2.signals.payment_retry_evaluation';

    const STATUS_CANCELED = 'canceled';
    const STATUS_COMPLETED = 'completed';
    const STATUS_EXPIRED = 'expired';
    const STATUS_MONITORING = 'monitoring';
}
