<?php

// File generated from our OpenAPI spec

namespace Stripe\EventData;

/**
 * @property string[] $invoices The IDs of the invoices that were generated by the tick for this Cadence.
 */
class V2BillingCadenceBilledEventData extends \Stripe\StripeObject {}
