<?php

// File generated from our OpenAPI spec

namespace Stripe\V2\Core;

/**
 * Events are generated to keep you informed of activity in your business account. APIs in the /v2 namespace generate <a href="https://docs.stripe.com/event-destinations#benefits-of-thin-events">thin events</a> which have small, unversioned payloads that include a reference to the ID of the object that has changed. The Events v2 API returns these new thin events. <a href="https://docs.stripe.com/event-destinations#fetch-data">Retrieve the event object</a> for additional data about the event. Use the related object ID in the event payload to <a href="https://docs.stripe.com/event-destinations#retrieve-the-object-associated-with-thin-events">fetch the API resource</a> of the object associated with the event. Comparatively, events generated by most API v1 include a versioned snapshot of an API object in their payload.
 *
 * @property string $id Unique identifier for the event.
 * @property string $object String representing the object's type. Objects of the same type share the same value of the object field.
 * @property null|string $context Authentication context needed to fetch the event or related object.
 * @property int $created Time at which the object was created.
 * @property bool $livemode Has the value <code>true</code> if the object exists in live mode or the value <code>false</code> if the object exists in test mode.
 * @property null|\Stripe\StripeObject $reason Reason for the event.
 * @property string $type The type of the event.
 */
class Event extends \Stripe\ApiResource
{
    const OBJECT_NAME = 'v2.core.event';
}
