<?php

namespace Stripe\Util;

class EventNotificationTypes
{
    const v2EventMapping = [
        // The beginning of the section generated from our OpenAPI spec
        \Stripe\Events\V1BillingMeterErrorReportTriggeredEventNotification::LOOKUP_TYPE => \Stripe\Events\V1BillingMeterErrorReportTriggeredEventNotification::class,
        \Stripe\Events\V1BillingMeterNoMeterFoundEventNotification::LOOKUP_TYPE => \Stripe\Events\V1BillingMeterNoMeterFoundEventNotification::class,
        \Stripe\Events\V2CoreAccountClosedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountClosedEventNotification::class,
        \Stripe\Events\V2CoreAccountCreatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountCreatedEventNotification::class,
        \Stripe\Events\V2CoreAccountUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountUpdatedEventNotification::class,
        \Stripe\Events\V2CoreAccountIncludingConfigurationCustomerCapabilityStatusUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingConfigurationCustomerCapabilityStatusUpdatedEventNotification::class,
        \Stripe\Events\V2CoreAccountIncludingConfigurationCustomerUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingConfigurationCustomerUpdatedEventNotification::class,
        \Stripe\Events\V2CoreAccountIncludingConfigurationMerchantCapabilityStatusUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingConfigurationMerchantCapabilityStatusUpdatedEventNotification::class,
        \Stripe\Events\V2CoreAccountIncludingConfigurationMerchantUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingConfigurationMerchantUpdatedEventNotification::class,
        \Stripe\Events\V2CoreAccountIncludingConfigurationRecipientCapabilityStatusUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingConfigurationRecipientCapabilityStatusUpdatedEventNotification::class,
        \Stripe\Events\V2CoreAccountIncludingConfigurationRecipientUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingConfigurationRecipientUpdatedEventNotification::class,
        \Stripe\Events\V2CoreAccountIncludingConfigurationStorerCapabilityStatusUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingConfigurationStorerCapabilityStatusUpdatedEventNotification::class,
        \Stripe\Events\V2CoreAccountIncludingConfigurationStorerUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingConfigurationStorerUpdatedEventNotification::class,
        \Stripe\Events\V2CoreAccountIncludingDefaultsUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingDefaultsUpdatedEventNotification::class,
        \Stripe\Events\V2CoreAccountIncludingIdentityUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingIdentityUpdatedEventNotification::class,
        \Stripe\Events\V2CoreAccountIncludingRequirementsUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingRequirementsUpdatedEventNotification::class,
        \Stripe\Events\V2CoreAccountLinkReturnedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountLinkReturnedEventNotification::class,
        \Stripe\Events\V2CoreAccountPersonCreatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountPersonCreatedEventNotification::class,
        \Stripe\Events\V2CoreAccountPersonDeletedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountPersonDeletedEventNotification::class,
        \Stripe\Events\V2CoreAccountPersonUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountPersonUpdatedEventNotification::class,
        \Stripe\Events\V2CoreEventDestinationPingEventNotification::LOOKUP_TYPE => \Stripe\Events\V2CoreEventDestinationPingEventNotification::class,
        \Stripe\Events\V2MoneyManagementAdjustmentCreatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementAdjustmentCreatedEventNotification::class,
        \Stripe\Events\V2MoneyManagementFinancialAccountCreatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementFinancialAccountCreatedEventNotification::class,
        \Stripe\Events\V2MoneyManagementFinancialAccountUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementFinancialAccountUpdatedEventNotification::class,
        \Stripe\Events\V2MoneyManagementFinancialAddressActivatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementFinancialAddressActivatedEventNotification::class,
        \Stripe\Events\V2MoneyManagementFinancialAddressFailedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementFinancialAddressFailedEventNotification::class,
        \Stripe\Events\V2MoneyManagementInboundTransferAvailableEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementInboundTransferAvailableEventNotification::class,
        \Stripe\Events\V2MoneyManagementInboundTransferBankDebitFailedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementInboundTransferBankDebitFailedEventNotification::class,
        \Stripe\Events\V2MoneyManagementInboundTransferBankDebitProcessingEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementInboundTransferBankDebitProcessingEventNotification::class,
        \Stripe\Events\V2MoneyManagementInboundTransferBankDebitQueuedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementInboundTransferBankDebitQueuedEventNotification::class,
        \Stripe\Events\V2MoneyManagementInboundTransferBankDebitReturnedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementInboundTransferBankDebitReturnedEventNotification::class,
        \Stripe\Events\V2MoneyManagementInboundTransferBankDebitSucceededEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementInboundTransferBankDebitSucceededEventNotification::class,
        \Stripe\Events\V2MoneyManagementOutboundPaymentCanceledEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundPaymentCanceledEventNotification::class,
        \Stripe\Events\V2MoneyManagementOutboundPaymentCreatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundPaymentCreatedEventNotification::class,
        \Stripe\Events\V2MoneyManagementOutboundPaymentFailedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundPaymentFailedEventNotification::class,
        \Stripe\Events\V2MoneyManagementOutboundPaymentPostedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundPaymentPostedEventNotification::class,
        \Stripe\Events\V2MoneyManagementOutboundPaymentReturnedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundPaymentReturnedEventNotification::class,
        \Stripe\Events\V2MoneyManagementOutboundPaymentUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundPaymentUpdatedEventNotification::class,
        \Stripe\Events\V2MoneyManagementOutboundTransferCanceledEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundTransferCanceledEventNotification::class,
        \Stripe\Events\V2MoneyManagementOutboundTransferCreatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundTransferCreatedEventNotification::class,
        \Stripe\Events\V2MoneyManagementOutboundTransferFailedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundTransferFailedEventNotification::class,
        \Stripe\Events\V2MoneyManagementOutboundTransferPostedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundTransferPostedEventNotification::class,
        \Stripe\Events\V2MoneyManagementOutboundTransferReturnedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundTransferReturnedEventNotification::class,
        \Stripe\Events\V2MoneyManagementOutboundTransferUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundTransferUpdatedEventNotification::class,
        \Stripe\Events\V2MoneyManagementPayoutMethodUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementPayoutMethodUpdatedEventNotification::class,
        \Stripe\Events\V2MoneyManagementReceivedCreditAvailableEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedCreditAvailableEventNotification::class,
        \Stripe\Events\V2MoneyManagementReceivedCreditFailedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedCreditFailedEventNotification::class,
        \Stripe\Events\V2MoneyManagementReceivedCreditReturnedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedCreditReturnedEventNotification::class,
        \Stripe\Events\V2MoneyManagementReceivedCreditSucceededEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedCreditSucceededEventNotification::class,
        \Stripe\Events\V2MoneyManagementReceivedDebitCanceledEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedDebitCanceledEventNotification::class,
        \Stripe\Events\V2MoneyManagementReceivedDebitFailedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedDebitFailedEventNotification::class,
        \Stripe\Events\V2MoneyManagementReceivedDebitPendingEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedDebitPendingEventNotification::class,
        \Stripe\Events\V2MoneyManagementReceivedDebitSucceededEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedDebitSucceededEventNotification::class,
        \Stripe\Events\V2MoneyManagementReceivedDebitUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedDebitUpdatedEventNotification::class,
        \Stripe\Events\V2MoneyManagementTransactionCreatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementTransactionCreatedEventNotification::class,
        \Stripe\Events\V2MoneyManagementTransactionUpdatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementTransactionUpdatedEventNotification::class,
        \Stripe\Events\V2PaymentsOffSessionPaymentAttemptFailedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2PaymentsOffSessionPaymentAttemptFailedEventNotification::class,
        \Stripe\Events\V2PaymentsOffSessionPaymentAttemptStartedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2PaymentsOffSessionPaymentAttemptStartedEventNotification::class,
        \Stripe\Events\V2PaymentsOffSessionPaymentAuthorizationAttemptFailedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2PaymentsOffSessionPaymentAuthorizationAttemptFailedEventNotification::class,
        \Stripe\Events\V2PaymentsOffSessionPaymentAuthorizationAttemptStartedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2PaymentsOffSessionPaymentAuthorizationAttemptStartedEventNotification::class,
        \Stripe\Events\V2PaymentsOffSessionPaymentCanceledEventNotification::LOOKUP_TYPE => \Stripe\Events\V2PaymentsOffSessionPaymentCanceledEventNotification::class,
        \Stripe\Events\V2PaymentsOffSessionPaymentCreatedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2PaymentsOffSessionPaymentCreatedEventNotification::class,
        \Stripe\Events\V2PaymentsOffSessionPaymentFailedEventNotification::LOOKUP_TYPE => \Stripe\Events\V2PaymentsOffSessionPaymentFailedEventNotification::class,
        \Stripe\Events\V2PaymentsOffSessionPaymentRequiresCaptureEventNotification::LOOKUP_TYPE => \Stripe\Events\V2PaymentsOffSessionPaymentRequiresCaptureEventNotification::class,
        \Stripe\Events\V2PaymentsOffSessionPaymentSucceededEventNotification::LOOKUP_TYPE => \Stripe\Events\V2PaymentsOffSessionPaymentSucceededEventNotification::class,
        // The end of the section generated from our OpenAPI spec
    ];
}
