<?php

namespace Stripe\Util;

class EventTypes
{
    const thinEventMapping = [
        // The beginning of the section generated from our OpenAPI spec
        \Stripe\Events\V2CoreAccountIncludingRequirementsUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingRequirementsUpdatedEvent::class,
        \Stripe\Events\V2CoreAccountLinkReturnedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountLinkReturnedEvent::class,
        \Stripe\Events\V2CoreAccountClosedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountClosedEvent::class,
        \Stripe\Events\V2CoreAccountCreatedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountCreatedEvent::class,
        \Stripe\Events\V2CoreAccountUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountUpdatedEvent::class,
        \Stripe\Events\V2CoreAccountIncludingDefaultsUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingDefaultsUpdatedEvent::class,
        \Stripe\Events\V2CoreAccountIncludingConfigurationCustomerCapabilityStatusUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingConfigurationCustomerCapabilityStatusUpdatedEvent::class,
        \Stripe\Events\V2CoreAccountIncludingConfigurationCustomerUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingConfigurationCustomerUpdatedEvent::class,
        \Stripe\Events\V2CoreAccountIncludingIdentityUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingIdentityUpdatedEvent::class,
        \Stripe\Events\V2CoreAccountPersonCreatedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountPersonCreatedEvent::class,
        \Stripe\Events\V2CoreAccountPersonDeletedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountPersonDeletedEvent::class,
        \Stripe\Events\V2CoreAccountPersonUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountPersonUpdatedEvent::class,
        \Stripe\Events\V2CoreAccountIncludingConfigurationMerchantCapabilityStatusUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingConfigurationMerchantCapabilityStatusUpdatedEvent::class,
        \Stripe\Events\V2CoreAccountIncludingConfigurationMerchantUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingConfigurationMerchantUpdatedEvent::class,
        \Stripe\Events\V2CoreAccountIncludingConfigurationRecipientCapabilityStatusUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingConfigurationRecipientCapabilityStatusUpdatedEvent::class,
        \Stripe\Events\V2CoreAccountIncludingConfigurationRecipientUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingConfigurationRecipientUpdatedEvent::class,
        \Stripe\Events\V2CoreAccountIncludingConfigurationStorerCapabilityStatusUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingConfigurationStorerCapabilityStatusUpdatedEvent::class,
        \Stripe\Events\V2CoreAccountIncludingConfigurationStorerUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreAccountIncludingConfigurationStorerUpdatedEvent::class,
        \Stripe\Events\V2MoneyManagementAdjustmentCreatedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementAdjustmentCreatedEvent::class,
        \Stripe\Events\V1BillingMeterErrorReportTriggeredEvent::LOOKUP_TYPE => \Stripe\Events\V1BillingMeterErrorReportTriggeredEvent::class,
        \Stripe\Events\V1BillingMeterNoMeterFoundEvent::LOOKUP_TYPE => \Stripe\Events\V1BillingMeterNoMeterFoundEvent::class,
        \Stripe\Events\V2MoneyManagementFinancialAccountCreatedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementFinancialAccountCreatedEvent::class,
        \Stripe\Events\V2MoneyManagementFinancialAccountUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementFinancialAccountUpdatedEvent::class,
        \Stripe\Events\V2MoneyManagementFinancialAddressActivatedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementFinancialAddressActivatedEvent::class,
        \Stripe\Events\V2MoneyManagementFinancialAddressFailedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementFinancialAddressFailedEvent::class,
        \Stripe\Events\V2MoneyManagementInboundTransferAvailableEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementInboundTransferAvailableEvent::class,
        \Stripe\Events\V2MoneyManagementInboundTransferBankDebitFailedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementInboundTransferBankDebitFailedEvent::class,
        \Stripe\Events\V2MoneyManagementInboundTransferBankDebitProcessingEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementInboundTransferBankDebitProcessingEvent::class,
        \Stripe\Events\V2MoneyManagementInboundTransferBankDebitQueuedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementInboundTransferBankDebitQueuedEvent::class,
        \Stripe\Events\V2MoneyManagementInboundTransferBankDebitReturnedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementInboundTransferBankDebitReturnedEvent::class,
        \Stripe\Events\V2MoneyManagementInboundTransferBankDebitSucceededEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementInboundTransferBankDebitSucceededEvent::class,
        \Stripe\Events\V2CoreEventDestinationPingEvent::LOOKUP_TYPE => \Stripe\Events\V2CoreEventDestinationPingEvent::class,
        \Stripe\Events\V2PaymentsOffSessionPaymentAuthorizationAttemptFailedEvent::LOOKUP_TYPE => \Stripe\Events\V2PaymentsOffSessionPaymentAuthorizationAttemptFailedEvent::class,
        \Stripe\Events\V2PaymentsOffSessionPaymentAuthorizationAttemptStartedEvent::LOOKUP_TYPE => \Stripe\Events\V2PaymentsOffSessionPaymentAuthorizationAttemptStartedEvent::class,
        \Stripe\Events\V2PaymentsOffSessionPaymentCanceledEvent::LOOKUP_TYPE => \Stripe\Events\V2PaymentsOffSessionPaymentCanceledEvent::class,
        \Stripe\Events\V2PaymentsOffSessionPaymentCreatedEvent::LOOKUP_TYPE => \Stripe\Events\V2PaymentsOffSessionPaymentCreatedEvent::class,
        \Stripe\Events\V2PaymentsOffSessionPaymentFailedEvent::LOOKUP_TYPE => \Stripe\Events\V2PaymentsOffSessionPaymentFailedEvent::class,
        \Stripe\Events\V2PaymentsOffSessionPaymentSucceededEvent::LOOKUP_TYPE => \Stripe\Events\V2PaymentsOffSessionPaymentSucceededEvent::class,
        \Stripe\Events\V2MoneyManagementOutboundPaymentCanceledEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundPaymentCanceledEvent::class,
        \Stripe\Events\V2MoneyManagementOutboundPaymentCreatedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundPaymentCreatedEvent::class,
        \Stripe\Events\V2MoneyManagementOutboundPaymentFailedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundPaymentFailedEvent::class,
        \Stripe\Events\V2MoneyManagementOutboundPaymentPostedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundPaymentPostedEvent::class,
        \Stripe\Events\V2MoneyManagementOutboundPaymentReturnedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundPaymentReturnedEvent::class,
        \Stripe\Events\V2MoneyManagementOutboundPaymentUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundPaymentUpdatedEvent::class,
        \Stripe\Events\V2MoneyManagementOutboundTransferCanceledEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundTransferCanceledEvent::class,
        \Stripe\Events\V2MoneyManagementOutboundTransferCreatedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundTransferCreatedEvent::class,
        \Stripe\Events\V2MoneyManagementOutboundTransferFailedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundTransferFailedEvent::class,
        \Stripe\Events\V2MoneyManagementOutboundTransferPostedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundTransferPostedEvent::class,
        \Stripe\Events\V2MoneyManagementOutboundTransferReturnedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundTransferReturnedEvent::class,
        \Stripe\Events\V2MoneyManagementOutboundTransferUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementOutboundTransferUpdatedEvent::class,
        \Stripe\Events\V2MoneyManagementPayoutMethodUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementPayoutMethodUpdatedEvent::class,
        \Stripe\Events\V2MoneyManagementReceivedCreditAvailableEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedCreditAvailableEvent::class,
        \Stripe\Events\V2MoneyManagementReceivedCreditFailedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedCreditFailedEvent::class,
        \Stripe\Events\V2MoneyManagementReceivedCreditReturnedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedCreditReturnedEvent::class,
        \Stripe\Events\V2MoneyManagementReceivedCreditSucceededEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedCreditSucceededEvent::class,
        \Stripe\Events\V2MoneyManagementReceivedDebitCanceledEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedDebitCanceledEvent::class,
        \Stripe\Events\V2MoneyManagementReceivedDebitFailedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedDebitFailedEvent::class,
        \Stripe\Events\V2MoneyManagementReceivedDebitPendingEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedDebitPendingEvent::class,
        \Stripe\Events\V2MoneyManagementReceivedDebitSucceededEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedDebitSucceededEvent::class,
        \Stripe\Events\V2MoneyManagementReceivedDebitUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementReceivedDebitUpdatedEvent::class,
        \Stripe\Events\V2MoneyManagementTransactionCreatedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementTransactionCreatedEvent::class,
        \Stripe\Events\V2MoneyManagementTransactionUpdatedEvent::LOOKUP_TYPE => \Stripe\Events\V2MoneyManagementTransactionUpdatedEvent::class,
        // The end of the section generated from our OpenAPI spec
    ];
}
